spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/cydeo/dev/user/**
#          filters:
#            - RewritePath=/cydeo/dev/user/(?<segment>.*)","/${segment}"
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://host.docker.internal:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8080/auth/realms/master/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

server:
  port: 8762

eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

