spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

server:
  port: 8762

eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/



