spring:
  application:
    name: project-service
  profiles:
    active: default
    #    initialization-mode: always
    data: classpath:init01.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/ticketing-app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

