
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



