#server:
#  port: 8761
#
#spring:
#  application:
#    name: eurekaserver
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka


server:
  port: 8761
eureka:
  instance:
    hostname: discovery-service-1
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka/
